# override this with `--build-arg BASE_IMAGE=...`
ARG BUILD_IMAGE=ekidd/rust-musl-builder

FROM ${BUILD_IMAGE} as build

# create empty project
RUN USER=root cargo new --bin app
RUN mv app/src . && rm -rf app

# manifests
ADD ./Cargo.toml .
ADD ./Cargo.lock .

# compile dev to get dependencies and cleanup boilerplate files
RUN cargo build --release
RUN rm src/*.rs
RUN rm target/x86_64-unknown-linux-musl/release/deps/csvbuttler*

# now copy over our source files
# note, that if I use ADD here, this layer is not used from cache
# for some reason
ADD . ./

# fix permissions
# RUN sudo chown -R rust:rust /home/rust

# build
RUN cargo build --release

# final image
FROM alpine:latest

# create an unprivileged user
RUN addgroup -g 1000 johndoe
RUN adduser -D -s /bin/sh -u 1000 -G johndoe johndoe


# copy the build artifact from the build stage
COPY --from=build \
    /home/rust/src/target/x86_64-unknown-linux-musl/release/csvbuttler \
    /usr/local/bin/

# change owner and run app as unprivileged user
RUN chown johndoe:johndoe /usr/local/bin/csvbuttler
USER johndoe

# expose default port
EXPOSE 8000
# set the startup command to run your binary
CMD csvbuttler -i 0.0.0.0 -d ";"
